name: finance_app
description: "A personal finance management app built with Flutter"
publish_to: "none"
version: 0.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Provides iOS-style icons for Cupertino widgets

  # Local Storage and File Handling
  shared_preferences: ^2.5.3 # For storing simple key-value pairs locally
  path_provider: ^2.1.5 # For accessing commonly used file paths
  file_picker: ^8.0.0 # For picking files from the device

  # Machine Learning and Media
  google_mlkit_text_recognition: ^0.15.0 # For text recognition using Google ML Kit
  image_picker: ^1.1.2 # For picking images from the gallery or camera

  # Permissions and Sharing
  permission_handler: ^11.2.0 # For handling runtime permissions
  share_plus: ^10.0.0 # For sharing content across apps

  # Firebase Services
  firebase_core: ^2.27.2 # Core Firebase SDK for initializing Firebase
  firebase_auth: ^4.18.0 # For Firebase authentication
  cloud_firestore: ^4.15.9 # For using Firestore database
  google_sign_in: ^6.2.0 # For Google Sign-In integration
  firebase_messaging: ^14.6.9 # For push notifications using Firebase Cloud Messaging

  # Social Authentication
  flutter_facebook_auth: ^6.0.0 # For Facebook authentication

  # Device Security
  local_auth: ^2.1.6 # For biometric authentication (e.g., fingerprint, face ID)

  # State Management
  flutter_bloc: ^8.1.4 # For state management using the BLoC pattern
  equatable: ^2.0.5 # For simplifying equality comparisons in Dart objects

  # UI and Formatting
  intl: ^0.19.0 # For internationalization and date formatting
  fl_chart: ^0.66.2 # For creating beautiful charts
  google_fonts: ^6.2.1 # For using Google Fonts in your app
  bloc: ^8.1.0 # For implementing the BLoC pattern
  provider: ^6.1.3 # For state management using the Provider pattern
  dynamic_color: ^1.7.0 # For dynamic theming based on system colors
  uuid: ^4.3.3 # For generating unique identifiers
  go_router: ^14.8.1 # For declarative navigation and routing
  flutter_spinkit: ^5.2.1 # For loading spinners and animations
  csv: ^6.0.0 # For working with CSV files

  # Dependency Injection
  get_it: ^8.0.3 # For dependency injection and service locator pattern

  # Flutter_localizations
  flutter_localizations:
    sdk: flutter # For enabling localization support in Flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  bloc_test: ^9.1.0
  # Removing firebase_auth_mocks as it's incompatible with firebase_auth ^4.18.0
  firebase_core_platform_interface: ^5.0.0
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
  flutter_flavorizr: ^2.2.1
  mockito: ^5.4.6
  build_runner: ^2.4.14

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/ # Directory for storing image assets
