name: finance_app
description: "A personcnal finance management app build with Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  shared_preferences: ^2.5.3

  # Firebase
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.9
  google_sign_in: ^6.2.0
  firebase_messaging: ^14.8.4
  flutter_facebook_auth: ^6.0.0

  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # UI and Formatting
  intl: ^0.19.0
  fl_chart: ^0.66.2
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  uuid: ^4.3.3
  go_router: ^14.8.1

  # Dependency Injection
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

assets:
  - assets/
