// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC07XF3NY7uH5RpGTeSwI5wz_kKuQfidGU',
    appId: '1:604592554761:android:e1aa37ad84eed38a4349d8',
    messagingSenderId: '604592554761',
    projectId: 'financial-management-b7043',
    storageBucket: 'financial-management-b7043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAayQRYOTHXZrdtGCnrywzKW9T-v2U1Lcs',
    appId: '1:604592554761:ios:7164f78c15134ca84349d8',
    messagingSenderId: '604592554761',
    projectId: 'financial-management-b7043',
    storageBucket: 'financial-management-b7043.firebasestorage.app',
    androidClientId: '604592554761-g62kienaac9nvthj78vphedukcltmdeg.apps.googleusercontent.com',
    iosClientId: '604592554761-6i5kmokl066ak8vqpm42lu8gr90c7g22.apps.googleusercontent.com',
    iosBundleId: 'com.io.ziblox.financeApp',
  );

}