// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEN-zmCBQ4xS23V7TKHJ5kevjzVTibHKM',
    appId: '1:409487606543:android:2bdc3b659c031bc8d5747a',
    messagingSenderId: '409487606543',
    projectId: 'financial-management-eb5b1',
    storageBucket: 'financial-management-eb5b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz9YC9xKnpEqJ8dcnrHt-doAHuCOSZFpw',
    appId: '1:409487606543:ios:98f53a824ef44b7ed5747a',
    messagingSenderId: '409487606543',
    projectId: 'financial-management-eb5b1',
    storageBucket: 'financial-management-eb5b1.firebasestorage.app',
    androidClientId: '409487606543-146ova5lfqqif2hsqs3j9mfn2s2chfu4.apps.googleusercontent.com',
    iosClientId: '409487606543-jo4img71k3c181ff1b0f7e9fpqc9bkni.apps.googleusercontent.com',
    iosBundleId: 'com.io.ziblox.financeApp',
  );
}
